#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

#easy_admin:
#    entities:
#        #List the entity class name you want to manage
#        - App\Entity\Conference
#        - App\Entity\Comment

easy_admin:
  site_name: Liste des conférences

  design:
    menu:
      - { route: "homepage", label: "Back to the website", icon: "home" }
      - { entity: "Conference", label: "Conferences", icon: "map-marker" }
      - { entity: "Comment", label: "Comments", icon: "comments" }
  entities:
    Conference:
      class: App\Entity\Conference
      list:
        fields:
          - year
          - city
          - { property: "isInternational", type: "boolean" }
        

    Comment:
      class: App\Entity\Comment
      list:
        fields:
          - author
          - { property: "createdAt", type: "datetime" }
          - { property: "note", type: "smallint" }

        sort: ["createdAt", "ASC"]
        filters: ["conference"]
      edit:
        fields:
          - { property: "conference" }
          - {
              property: "createdAt",
              type: datetime,
              type_options: { attr: { readonly: true } },
            }
          - "author"
          - { property: "note"}
          - { property: "email", type: "email" }
          - text
